# Generated by Django 5.1.2 on 2024-11-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_category', models.CharField(max_length=50)),
                ('product_price', models.FloatField()),
                ('product_qty', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='products/')),
                ('product_description', models.TextField()),
            ],
        ),
    ]
